export type CurriculumKind = 'class' | 'primitive';
export type CurriculumStatus = 'implemented' | 'planned';
export type CurriculumTrack = 'numbered-class' | 'alphabetical-primitive' | 'reference-primitive';
export type VisualGrammar =
  'precise-2d' | 'restrained-2.5d' | 'mixed-2d-and-2.5d' | 'timeline' | 'reference-only';

export interface CurriculumImplementation {
  docPath: string;
  route: string;
  references: readonly string[];
}

export interface CurriculumModule {
  id: string;
  title: string;
  kind: CurriculumKind;
  track: CurriculumTrack;
  sequencePosition: number;
  status: CurriculumStatus;
  centralQuestionOrSkill: string;
  prerequisites: readonly string[];
  concepts: readonly string[];
  deferred: readonly string[];
  visualGrammar: VisualGrammar;
  learnerOutcome: string;
  unlocks: readonly string[];
  implementation: CurriculumImplementation | null;
  scaffoldPath: string | null;
}

/** The only learner-facing interleaving in the first frozen curriculum pass. */
export const CURRICULUM_SEQUENCE = [
  'class-0',
  'primitive-a',
  'class-1',
  'primitive-b',
  'class-2',
  'primitive-c',
  'class-3',
  'primitive-d',
  'class-4',
  'primitive-e',
  'class-5',
  'primitive-f',
  'class-6',
  'primitive-g',
  'class-7',
] as const;

/** Reserved reference primitives; these are not interleaved into the first pass. */
export const REFERENCE_PRIMITIVES = ['primitive-h', 'primitive-i', 'primitive-j', 'primitive-k'] as const;

export const CURRICULUM_MODULES = [
  {
    id: 'class-0',
    title: 'Clase 0 — El modelo mental de una GPU',
    kind: 'class',
    track: 'numbered-class',
    sequencePosition: 1,
    status: 'implemented',
    centralQuestionOrSkill: 'How is work divided between data, threads, blocks, and the GPU?',
    prerequisites: [],
    concepts: [
      'host and device',
      'data and elements',
      'grid',
      'blocks',
      'threads',
      'inactive threads',
      'bounds',
      'partial final block',
    ],
    deferred: ['warps', 'scheduling', 'memory hierarchy', 'occupancy', 'timing and performance'],
    visualGrammar: 'precise-2d',
    learnerOutcome:
      'Explain the grid/block/thread hierarchy and identify inactive threads in a partial final block.',
    unlocks: ['primitive-a', 'class-1'],
    implementation: {
      docPath: 'apps/docs/clase-0/modelo-mental-gpu.md',
      route: '/clase-0/modelo-mental-gpu',
      references: ['packages/visuals/src/ModeloMentalGpu.vue', 'packages/core/src/chunk-flow'],
    },
    scaffoldPath: null,
  },
  {
    id: 'primitive-a',
    title: 'Primitiva A — cudaMalloc',
    kind: 'primitive',
    track: 'alphabetical-primitive',
    sequencePosition: 2,
    status: 'implemented',
    centralQuestionOrSkill: 'Understand exactly what cudaMalloc changes and what it does not change.',
    prerequisites: ['class-0'],
    concepts: [
      'device allocation',
      'pointer output',
      'byte count',
      'uninitialized memory',
      'allocation is not data movement',
    ],
    deferred: ['cudaFree', 'memory initialization', 'kernel execution', 'addresses and timing'],
    visualGrammar: 'precise-2d',
    learnerOutcome:
      'Predict the before/action/after state of a successful allocation and distinguish reserved space from initialized data.',
    unlocks: ['class-1'],
    implementation: {
      docPath: 'apps/docs/clases/cuda-malloc.md',
      route: '/clases/cuda-malloc',
      references: [
        'packages/visuals/src/ClaseCudaMalloc.vue',
        'packages/core/src/cuda-malloc',
        'native/examples/vector-add',
        'native/exercises/01-vector-add',
        'anki/cards/01-cuda-malloc.yaml',
      ],
    },
    scaffoldPath: null,
  },
  {
    id: 'class-1',
    title: 'Clase 1 — Índice global y suma de vectores',
    kind: 'class',
    track: 'numbered-class',
    sequencePosition: 3,
    status: 'implemented',
    centralQuestionOrSkill: 'How does each thread determine which data element belongs to it?',
    prerequisites: ['class-0', 'primitive-a'],
    concepts: ['blockIdx.x', 'blockDim.x', 'threadIdx.x', 'global index', 'bounds guard', 'vector addition'],
    deferred: ['coalescing analysis', 'shared-memory reuse', 'asynchronous transfers', 'performance claims'],
    visualGrammar: 'precise-2d',
    learnerOutcome:
      'Derive blockIdx.x * blockDim.x + threadIdx.x, guard the tail, and verify vector addition against a CPU oracle.',
    unlocks: ['primitive-b', 'class-2'],
    implementation: {
      docPath: 'apps/docs/leccion/indice-global-suma-vectores.md',
      route: '/leccion/indice-global-suma-vectores',
      references: [
        'packages/visuals/src/ExploradorIndiceGlobal.vue',
        'packages/core/src/thread-index',
        'native/examples/vector-add',
        'native/exercises/01-vector-add',
        'anki/cards/01-indice-global.yaml',
      ],
    },
    scaffoldPath: null,
  },
  {
    id: 'primitive-b',
    title: 'Primitiva B — cudaMemcpy',
    kind: 'primitive',
    track: 'alphabetical-primitive',
    sequencePosition: 4,
    status: 'implemented',
    centralQuestionOrSkill: 'Understand explicit host-to-device and device-to-host movement.',
    prerequisites: ['class-1'],
    concepts: [
      'source',
      'destination',
      'transfer direction',
      'bytes transferred',
      'values before and after',
      'movement is not allocation',
    ],
    deferred: ['cudaMemcpyAsync', 'streams', 'overlap', 'peer-to-peer transfers'],
    visualGrammar: 'precise-2d',
    learnerOutcome:
      'Name the source, destination, direction, and byte count of a synchronous copy and predict which values change.',
    unlocks: ['class-2'],
    implementation: {
      docPath: 'apps/docs/clases/cuda-memcpy.md',
      route: '/clases/cuda-memcpy',
      references: [
        'packages/visuals/src/ClaseCudaMemcpy.vue',
        'packages/core/src/cuda-memcpy',
        'native/examples/cuda-memcpy',
        'anki/cards/03-cuda-memcpy.yaml',
      ],
    },
    scaffoldPath: null,
  },
  {
    id: 'class-2',
    title: 'Clase 2 — Reducción paralela',
    kind: 'class',
    track: 'numbered-class',
    sequencePosition: 5,
    status: 'implemented',
    centralQuestionOrSkill: 'How do N values become one without using one shared serial accumulator?',
    prerequisites: ['class-1', 'primitive-b'],
    concepts: [
      'disjoint pair assignment',
      'reduction passes',
      'tree structure',
      'odd tails',
      'correctness before performance',
      'reduction result',
    ],
    deferred: ['warp shuffle', 'bank-conflict tuning', 'library reductions', 'benchmark comparisons'],
    visualGrammar: 'precise-2d',
    learnerOutcome:
      'Trace a pairwise reduction, handle odd tails, and explain why a shared serial accumulator is a correctness problem.',
    unlocks: ['primitive-c', 'class-3'],
    implementation: {
      docPath: 'apps/docs/leccion/reduccion-paralela.md',
      route: '/leccion/reduccion-paralela',
      references: [
        'packages/visuals/src/LaboratorioReduccion.vue',
        'packages/core/src/reduction',
        'native/examples/reduction',
        'native/exercises/02-reduction',
        'anki/cards/02-reduccion.yaml',
      ],
    },
    scaffoldPath: null,
  },
  {
    id: 'primitive-c',
    title: 'Primitiva C — __syncthreads()',
    kind: 'primitive',
    track: 'alphabetical-primitive',
    sequencePosition: 6,
    status: 'planned',
    centralQuestionOrSkill: 'Understand what a block-wide barrier guarantees and what it does not guarantee.',
    prerequisites: ['class-2'],
    concepts: [
      'threads reaching a barrier',
      'same-block scope',
      'no inter-block synchronization',
      'divergent barrier use',
      'before, waiting, and released states',
    ],
    deferred: [
      'cooperative groups',
      'grid-wide barriers',
      'warp-level synchronization',
      'performance tuning',
    ],
    visualGrammar: 'precise-2d',
    learnerOutcome:
      'State which threads may proceed after __syncthreads() and reject invalid or divergent barrier assumptions.',
    unlocks: ['class-3'],
    implementation: null,
    scaffoldPath: 'docs/curriculum/modules/primitive-c-syncthreads.md',
  },
  {
    id: 'class-3',
    title: 'Clase 3 — Memoria de GPU y patrones de acceso',
    kind: 'class',
    track: 'numbered-class',
    sequencePosition: 7,
    status: 'planned',
    centralQuestionOrSkill: 'Why does where and how threads access memory matter?',
    prerequisites: ['class-2', 'primitive-c'],
    concepts: [
      'registers',
      'shared memory',
      'global memory',
      'access patterns',
      'contiguous access',
      'strided access',
      'introductory coalescing',
      'data reuse',
    ],
    deferred: [
      'advanced occupancy tuning',
      'detailed cache policy',
      'bank-conflict optimization',
      'architecture-specific performance claims',
    ],
    visualGrammar: 'precise-2d',
    learnerOutcome:
      'Compare contiguous and strided access, identify the role of registers/shared/global memory, and describe simple reuse.',
    unlocks: ['primitive-d', 'class-4'],
    implementation: null,
    scaffoldPath: 'docs/curriculum/modules/class-3-memory-access.md',
  },
  {
    id: 'primitive-d',
    title: 'Primitiva D — __shared__',
    kind: 'primitive',
    track: 'alphabetical-primitive',
    sequencePosition: 8,
    status: 'planned',
    centralQuestionOrSkill: 'Understand how threads in one block cooperatively stage reusable data.',
    prerequisites: ['class-3'],
    concepts: [
      'shared allocation',
      'block scope',
      'global-to-shared movement',
      'reuse',
      'synchronization where relevant',
    ],
    deferred: [
      'bank-conflict tuning',
      'dynamic allocation edge cases',
      'warp-specialized designs',
      'performance numbers',
    ],
    visualGrammar: 'precise-2d',
    learnerOutcome:
      'Explain what shared storage is scoped to, what data must be staged, and when cooperation needs synchronization.',
    unlocks: ['class-4'],
    implementation: null,
    scaffoldPath: 'docs/curriculum/modules/primitive-d-shared.md',
  },
  {
    id: 'class-4',
    title: 'Clase 4 — Multiplicación de matrices con tiles',
    kind: 'class',
    track: 'numbered-class',
    sequencePosition: 9,
    status: 'planned',
    centralQuestionOrSkill:
      'How can a GPU reuse matrix data strategically instead of repeatedly fetching the same values?',
    prerequisites: ['class-3', 'primitive-d'],
    concepts: [
      'matrix multiplication recap',
      'one C[i,j] from one row and one column',
      'matrix tiles',
      'block cooperation',
      'shared-memory tiling',
      'data reuse',
      'load/compute synchronization',
    ],
    deferred: [
      'tensor cores',
      'advanced layouts',
      'autotuning',
      'benchmark claims',
      'production GEMM libraries',
    ],
    visualGrammar: 'mixed-2d-and-2.5d',
    learnerOutcome:
      'Trace one output element through tiled loads and compute phases, explain reuse, and identify synchronization boundaries.',
    unlocks: ['primitive-e', 'class-5'],
    implementation: null,
    scaffoldPath: 'docs/curriculum/modules/class-4-tiled-matrix-multiplication.md',
  },
  {
    id: 'primitive-e',
    title: 'Primitiva E — atomicAdd',
    kind: 'primitive',
    track: 'alphabetical-primitive',
    sequencePosition: 10,
    status: 'planned',
    centralQuestionOrSkill: 'Understand how multiple threads safely update one shared location.',
    prerequisites: ['class-4'],
    concepts: [
      'race condition',
      'atomic update',
      'correctness',
      'contention',
      'atomics are not automatically the best algorithm',
    ],
    deferred: [
      'lock-free custom protocols',
      'system-scope atomics',
      'performance rankings',
      'library-specific alternatives',
    ],
    visualGrammar: 'precise-2d',
    learnerOutcome:
      'Distinguish a lost update from an atomic update and explain why correctness does not remove contention.',
    unlocks: ['class-5'],
    implementation: null,
    scaffoldPath: 'docs/curriculum/modules/primitive-e-atomic-add.md',
  },
  {
    id: 'class-5',
    title: 'Clase 5 — Atomics, histogramas y contención',
    kind: 'class',
    track: 'numbered-class',
    sequencePosition: 11,
    status: 'planned',
    centralQuestionOrSkill: 'What happens when many threads need the same output location?',
    prerequisites: ['class-4', 'primitive-e'],
    concepts: [
      'histogram-style updates',
      'conflicting writes',
      'atomic correctness',
      'contention',
      'per-block strategies conceptually',
      'correctness versus scalability',
    ],
    deferred: [
      'full production histogram optimization',
      'architecture-specific contention models',
      'benchmark comparisons',
      'new synchronization APIs',
    ],
    visualGrammar: 'precise-2d',
    learnerOutcome:
      'Diagnose conflicting writes, choose atomics for correctness, and reason about contention and per-block aggregation.',
    unlocks: ['primitive-f', 'class-6'],
    implementation: null,
    scaffoldPath: 'docs/curriculum/modules/class-5-atomics-histograms.md',
  },
  {
    id: 'primitive-f',
    title: 'Primitiva F — cudaMemcpyAsync',
    kind: 'primitive',
    track: 'alphabetical-primitive',
    sequencePosition: 12,
    status: 'planned',
    centralQuestionOrSkill: 'Understand what it means to initiate a transfer asynchronously.',
    prerequisites: ['class-5'],
    concepts: [
      'enqueueing work',
      'completion is not immediate',
      'stream ordering',
      'synchronization before dependent use',
    ],
    deferred: [
      'multi-stream overlap strategies',
      'pinned-memory performance details',
      'CUDA graphs',
      'benchmark numbers',
    ],
    visualGrammar: 'timeline',
    learnerOutcome:
      'Separate enqueueing from completion and identify the synchronization needed before consuming transferred data.',
    unlocks: ['class-6'],
    implementation: null,
    scaffoldPath: 'docs/curriculum/modules/primitive-f-cuda-memcpy-async.md',
  },
  {
    id: 'class-6',
    title: 'Clase 6 — Streams y solapamiento',
    kind: 'class',
    track: 'numbered-class',
    sequencePosition: 13,
    status: 'planned',
    centralQuestionOrSkill: 'How can independent GPU work and transfers be organized as a pipeline?',
    prerequisites: ['class-5', 'primitive-f'],
    concepts: [
      'stream ordering',
      'independent streams',
      'host-device transfer timeline',
      'kernel timeline',
      'overlap concept',
      'dependencies',
      'explicit waiting',
    ],
    deferred: [
      'CUDA graphs',
      'multi-device scheduling',
      'throughput benchmarks',
      'implicit synchronization catalog',
    ],
    visualGrammar: 'timeline',
    learnerOutcome:
      'Draw a dependency-aware stream timeline and explain which work may overlap without claiming automatic concurrency.',
    unlocks: ['primitive-g', 'class-7'],
    implementation: null,
    scaffoldPath: 'docs/curriculum/modules/class-6-streams-overlap.md',
  },
  {
    id: 'primitive-g',
    title: 'Primitiva G — sincronización de stream y device',
    kind: 'primitive',
    track: 'alphabetical-primitive',
    sequencePosition: 14,
    status: 'planned',
    centralQuestionOrSkill: 'Know what scope is being waited on and when synchronization is actually needed.',
    prerequisites: ['class-6'],
    concepts: [
      'stream-local waiting',
      'device-wide waiting',
      'dependency boundaries',
      'avoiding unnecessary global synchronization',
    ],
    deferred: [
      'events as a measurement system',
      'host callbacks',
      'cooperative launch synchronization',
      'performance claims',
    ],
    visualGrammar: 'timeline',
    learnerOutcome:
      'Choose between stream-local and device-wide waiting and justify the dependency boundary being enforced.',
    unlocks: ['class-7'],
    implementation: null,
    scaffoldPath: 'docs/curriculum/modules/primitive-g-stream-device-synchronization.md',
  },
  {
    id: 'class-7',
    title: 'Clase 7 — De correcto a eficiente',
    kind: 'class',
    track: 'numbered-class',
    sequencePosition: 15,
    status: 'planned',
    centralQuestionOrSkill: 'How do we reason systematically about improving a correct GPU implementation?',
    prerequisites: ['class-6', 'primitive-g'],
    concepts: [
      'correct naive implementation',
      'indexing and memory access',
      'shared-memory reuse',
      'synchronization',
      'appropriate atomics',
      'appropriate overlap',
      'tradeoff reasoning',
    ],
    deferred: [
      'new API catalogues',
      'unmeasured benchmark numbers',
      'universal optimization rules',
      'architecture-specific tuning recipes',
    ],
    visualGrammar: 'mixed-2d-and-2.5d',
    learnerOutcome:
      'Explain what changed, why correctness remains valid, which bottleneck is addressed, and what tradeoff was introduced.',
    unlocks: [],
    implementation: null,
    scaffoldPath: 'docs/curriculum/modules/class-7-correct-to-efficient.md',
  },
  {
    id: 'primitive-h',
    title: 'Primitiva H — cudaFree',
    kind: 'primitive',
    track: 'reference-primitive',
    sequencePosition: 16,
    status: 'planned',
    centralQuestionOrSkill:
      'Reserve the release operation as a future reference module for allocation lifetime.',
    prerequisites: ['primitive-a'],
    concepts: ['allocation lifetime', 'release operation', 'pointer ownership boundary'],
    deferred: ['allocator performance', 'memory pools', 'unified-memory policy'],
    visualGrammar: 'reference-only',
    learnerOutcome:
      'Future module: explain when an allocation is released and what lifetime obligation follows cudaMalloc.',
    unlocks: [],
    implementation: null,
    scaffoldPath: 'docs/curriculum/modules/primitive-h-cuda-free.md',
  },
  {
    id: 'primitive-i',
    title: 'Primitiva I — cudaMemset',
    kind: 'primitive',
    track: 'reference-primitive',
    sequencePosition: 17,
    status: 'planned',
    centralQuestionOrSkill: 'Reserve the byte-pattern initialization operation as a future reference module.',
    prerequisites: ['primitive-a'],
    concepts: ['device memory initialization', 'byte pattern', 'allocation versus initialization'],
    deferred: ['typed fill semantics', 'performance comparisons', 'large-scale initialization strategies'],
    visualGrammar: 'reference-only',
    learnerOutcome: 'Future module: distinguish writing a byte pattern from writing typed numeric values.',
    unlocks: [],
    implementation: null,
    scaffoldPath: 'docs/curriculum/modules/primitive-i-cuda-memset.md',
  },
  {
    id: 'primitive-j',
    title: 'Primitiva J — cudaGetLastError',
    kind: 'primitive',
    track: 'reference-primitive',
    sequencePosition: 18,
    status: 'planned',
    centralQuestionOrSkill: 'Reserve post-launch error inspection as a future reference module.',
    prerequisites: ['class-1'],
    concepts: ['error state inspection', 'launch-error boundary', 'explicit error handling'],
    deferred: ['complete CUDA error taxonomy', 'debugger workflows', 'fault injection'],
    visualGrammar: 'reference-only',
    learnerOutcome:
      'Future module: identify what an error query can reveal and where it belongs in a checked launch path.',
    unlocks: [],
    implementation: null,
    scaffoldPath: 'docs/curriculum/modules/primitive-j-cuda-get-last-error.md',
  },
  {
    id: 'primitive-k',
    title: 'Primitiva K — cudaEventRecord y medición de tiempo',
    kind: 'primitive',
    track: 'reference-primitive',
    sequencePosition: 19,
    status: 'planned',
    centralQuestionOrSkill:
      'Reserve event recording and elapsed-time measurement as a future reference module.',
    prerequisites: ['primitive-f', 'class-6'],
    concepts: ['event placement', 'elapsed-time interval', 'measurement boundary'],
    deferred: ['published benchmarks', 'statistical benchmarking methodology', 'cross-device comparisons'],
    visualGrammar: 'timeline',
    learnerOutcome:
      'Future module: define a measured interval and keep kernel timing separate from transfer timing.',
    unlocks: [],
    implementation: null,
    scaffoldPath: 'docs/curriculum/modules/primitive-k-cuda-events.md',
  },
] as const satisfies readonly CurriculumModule[];

export const CURRICULUM_MANIFEST = Object.freeze({
  sequence: CURRICULUM_SEQUENCE,
  referencePrimitives: REFERENCE_PRIMITIVES,
  modules: CURRICULUM_MODULES,
});
